# Deploy by sending dispatch signal to internal CD repo
name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'build.R'
  workflow_dispatch:
jobs:
  deploy:
    if: ${{ github.repository == 'abbvie-external/OmicNavigatorExample' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: abbvie-internal/OmicNavigatorCD
          event-type: deploy-example-package
          # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          client-payload: '{
            "repository": "${{ github.repository }}",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}"
          }'
